# coding: utf-8

import re  # noqa: F401
import warnings  # noqa: F401

from aspose_barcode_cloud.api_client import ApiClient


class GenerateApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/OpenAPITools/openapi-generator
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client
        # Authentication setting
        self.auth_settings = ["JWT"]

    def generate(
        self,
        barcode_type,
        data,
        data_type=None,
        barcode_image_params=None,
        qr_params=None,
        code128_params=None,
        pdf417_params=None,
        async_req=False,
        **kwargs
    ):
        """Generate a barcode using a GET request with parameters in the route and query string.

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = GenerateApi().generate(barcode_type, data, async_req=True)
        >>> result = thread.get()

        :param EncodeBarcodeType barcode_type: Type of barcode to generate. # noqa: E501
        :param str data: String that represents the data to encode. # noqa: E501
        :param EncodeDataType data_type: Type of data to encode. Default value: StringData. # noqa: E501
        :param BarcodeImageParams barcode_image_params: Grouped BarcodeImageParams parameters. # noqa: E501
        :param QrParams qr_params: Grouped QrParams parameters. # noqa: E501
        :param Code128Params code128_params: Grouped Code128Params parameters. # noqa: E501
        :param Pdf417Params pdf417_params: Grouped Pdf417Params parameters. # noqa: E501
        :param async_req bool
        :return: bytearray
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if async_req:
            return self.generate_with_http_info(
                barcode_type,
                data,
                data_type=data_type,
                barcode_image_params=barcode_image_params,
                qr_params=qr_params,
                code128_params=code128_params,
                pdf417_params=pdf417_params,
                **kwargs
            )
        else:
            data = self.generate_with_http_info(
                barcode_type,
                data,
                data_type=data_type,
                barcode_image_params=barcode_image_params,
                qr_params=qr_params,
                code128_params=code128_params,
                pdf417_params=pdf417_params,
                **kwargs
            )
            return data

    def generate_with_http_info(self, barcode_type, data, **kwargs):
        """Generate a barcode using a GET request with parameters in the route and query string.

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = GenerateApi().generate_with_http_info(barcode_type, data, async_req=True)
        >>> result = thread.get()

        :param EncodeBarcodeType barcode_type: Type of barcode to generate. # noqa: E501
        :param str data: String that represents the data to encode. # noqa: E501
        :return: bytearray
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = {
            "barcode_type",
            "data",
            "data_type",
            "barcode_image_params",
            "qr_params",
            "code128_params",
            "pdf417_params",
        }
        all_params.add("async_req")
        all_params.add("_return_http_data_only")
        all_params.add("_preload_content")
        all_params.add("_request_timeout")

        params = locals()
        for key, val in params["kwargs"].items():
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s'" " to method generate" % key)
            if val is None:
                continue

            params[key] = val
        del params["kwargs"]
        if "barcode_image_params" in params and params["barcode_image_params"].image_format is not None:
            params["image_format"] = params["barcode_image_params"].image_format
        if "barcode_image_params" in params and params["barcode_image_params"].text_location is not None:
            params["text_location"] = params["barcode_image_params"].text_location
        if "barcode_image_params" in params and params["barcode_image_params"].foreground_color is not None:
            params["foreground_color"] = params["barcode_image_params"].foreground_color
        if "barcode_image_params" in params and params["barcode_image_params"].background_color is not None:
            params["background_color"] = params["barcode_image_params"].background_color
        if "barcode_image_params" in params and params["barcode_image_params"].units is not None:
            params["units"] = params["barcode_image_params"].units
        if "barcode_image_params" in params and params["barcode_image_params"].resolution is not None:
            params["resolution"] = params["barcode_image_params"].resolution
        if "barcode_image_params" in params and params["barcode_image_params"].image_height is not None:
            params["image_height"] = params["barcode_image_params"].image_height
        if "barcode_image_params" in params and params["barcode_image_params"].image_width is not None:
            params["image_width"] = params["barcode_image_params"].image_width
        if "barcode_image_params" in params and params["barcode_image_params"].rotation_angle is not None:
            params["rotation_angle"] = params["barcode_image_params"].rotation_angle
        if "qr_params" in params and params["qr_params"].qr_encode_mode is not None:
            params["qr_encode_mode"] = params["qr_params"].qr_encode_mode
        if "qr_params" in params and params["qr_params"].qr_error_level is not None:
            params["qr_error_level"] = params["qr_params"].qr_error_level
        if "qr_params" in params and params["qr_params"].qr_version is not None:
            params["qr_version"] = params["qr_params"].qr_version
        if "qr_params" in params and params["qr_params"].qr_eci_encoding is not None:
            params["qr_eci_encoding"] = params["qr_params"].qr_eci_encoding
        if "qr_params" in params and params["qr_params"].qr_aspect_ratio is not None:
            params["qr_aspect_ratio"] = params["qr_params"].qr_aspect_ratio
        if "qr_params" in params and params["qr_params"].micro_qr_version is not None:
            params["micro_qr_version"] = params["qr_params"].micro_qr_version
        if "qr_params" in params and params["qr_params"].rect_micro_qr_version is not None:
            params["rect_micro_qr_version"] = params["qr_params"].rect_micro_qr_version
        if "code128_params" in params and params["code128_params"].code128_encode_mode is not None:
            params["code128_encode_mode"] = params["code128_params"].code128_encode_mode
        if "pdf417_params" in params and params["pdf417_params"].pdf417_encode_mode is not None:
            params["pdf417_encode_mode"] = params["pdf417_params"].pdf417_encode_mode
        if "pdf417_params" in params and params["pdf417_params"].pdf417_error_level is not None:
            params["pdf417_error_level"] = params["pdf417_params"].pdf417_error_level
        if "pdf417_params" in params and params["pdf417_params"].pdf417_truncate is not None:
            params["pdf417_truncate"] = params["pdf417_params"].pdf417_truncate
        if "pdf417_params" in params and params["pdf417_params"].pdf417_columns is not None:
            params["pdf417_columns"] = params["pdf417_params"].pdf417_columns
        if "pdf417_params" in params and params["pdf417_params"].pdf417_rows is not None:
            params["pdf417_rows"] = params["pdf417_params"].pdf417_rows
        if "pdf417_params" in params and params["pdf417_params"].pdf417_aspect_ratio is not None:
            params["pdf417_aspect_ratio"] = params["pdf417_params"].pdf417_aspect_ratio
        if "pdf417_params" in params and params["pdf417_params"].pdf417_eci_encoding is not None:
            params["pdf417_eci_encoding"] = params["pdf417_params"].pdf417_eci_encoding
        if "pdf417_params" in params and params["pdf417_params"].pdf417_is_reader_initialization is not None:
            params["pdf417_is_reader_initialization"] = params["pdf417_params"].pdf417_is_reader_initialization
        if "pdf417_params" in params and params["pdf417_params"].pdf417_macro_characters is not None:
            params["pdf417_macro_characters"] = params["pdf417_params"].pdf417_macro_characters
        if "pdf417_params" in params and params["pdf417_params"].pdf417_is_linked is not None:
            params["pdf417_is_linked"] = params["pdf417_params"].pdf417_is_linked
        if "pdf417_params" in params and params["pdf417_params"].pdf417_is_code128_emulation is not None:
            params["pdf417_is_code128_emulation"] = params["pdf417_params"].pdf417_is_code128_emulation
        # verify the required parameter "barcode_type" is set
        if "barcode_type" not in params or params["barcode_type"] is None:
            raise ValueError("Missing the required parameter 'barcode_type' when calling 'generate'")
        # verify the required parameter "data" is set
        if "data" not in params or params["data"] is None:
            raise ValueError("Missing the required parameter 'data' when calling 'generate'")

        if "resolution" in params and params["resolution"] > 100000:
            raise ValueError(
                "Invalid value for parameter 'resolution' when calling 'generate', must be a value less than or equal to '100000'"
            )
        if "resolution" in params and params["resolution"] < 1:
            raise ValueError(
                "Invalid value for parameter 'resolution' when calling 'generate', must be a value greater than or equal to '1'"
            )
        if "qr_aspect_ratio" in params and params["qr_aspect_ratio"] > 1:
            raise ValueError(
                "Invalid value for parameter 'qr_aspect_ratio' when calling 'generate', must be a value less than or equal to '1'"
            )
        if "qr_aspect_ratio" in params and params["qr_aspect_ratio"] < 0.001:
            raise ValueError(
                "Invalid value for parameter 'qr_aspect_ratio' when calling 'generate', must be a value greater than or equal to '0.001'"
            )
        if "pdf417_columns" in params and params["pdf417_columns"] > 30:
            raise ValueError(
                "Invalid value for parameter 'pdf417_columns' when calling 'generate', must be a value less than or equal to '30'"
            )
        if "pdf417_columns" in params and params["pdf417_columns"] < 0:
            raise ValueError(
                "Invalid value for parameter 'pdf417_columns' when calling 'generate', must be a value greater than or equal to '0'"
            )
        if "pdf417_rows" in params and params["pdf417_rows"] > 90:
            raise ValueError(
                "Invalid value for parameter 'pdf417_rows' when calling 'generate', must be a value less than or equal to '90'"
            )
        if "pdf417_rows" in params and params["pdf417_rows"] < 0:
            raise ValueError(
                "Invalid value for parameter 'pdf417_rows' when calling 'generate', must be a value greater than or equal to '0'"
            )
        if "pdf417_aspect_ratio" in params and params["pdf417_aspect_ratio"] > 10:
            raise ValueError(
                "Invalid value for parameter 'pdf417_aspect_ratio' when calling 'generate', must be a value less than or equal to '10'"
            )
        if "pdf417_aspect_ratio" in params and params["pdf417_aspect_ratio"] < 2:
            raise ValueError(
                "Invalid value for parameter 'pdf417_aspect_ratio' when calling 'generate', must be a value greater than or equal to '2'"
            )
        collection_formats = {}

        path_params = {}
        if "barcode_type" in params:
            path_params["barcodeType"] = params["barcode_type"]

        query_params = []
        if "data_type" in params:
            query_params.append(("dataType", params["data_type"]))
        if "data" in params:
            query_params.append(("data", params["data"]))
        if "image_format" in params:
            query_params.append(("imageFormat", params["image_format"]))
        if "text_location" in params:
            query_params.append(("textLocation", params["text_location"]))
        if "foreground_color" in params:
            query_params.append(("foregroundColor", params["foreground_color"]))
        if "background_color" in params:
            query_params.append(("backgroundColor", params["background_color"]))
        if "units" in params:
            query_params.append(("units", params["units"]))
        if "resolution" in params:
            query_params.append(("resolution", params["resolution"]))
        if "image_height" in params:
            query_params.append(("imageHeight", params["image_height"]))
        if "image_width" in params:
            query_params.append(("imageWidth", params["image_width"]))
        if "rotation_angle" in params:
            query_params.append(("rotationAngle", params["rotation_angle"]))
        if "qr_encode_mode" in params:
            query_params.append(("qrEncodeMode", params["qr_encode_mode"]))
        if "qr_error_level" in params:
            query_params.append(("qrErrorLevel", params["qr_error_level"]))
        if "qr_version" in params:
            query_params.append(("qrVersion", params["qr_version"]))
        if "qr_eci_encoding" in params:
            query_params.append(("qrECIEncoding", params["qr_eci_encoding"]))
        if "qr_aspect_ratio" in params:
            query_params.append(("qrAspectRatio", params["qr_aspect_ratio"]))
        if "micro_qr_version" in params:
            query_params.append(("microQRVersion", params["micro_qr_version"]))
        if "rect_micro_qr_version" in params:
            query_params.append(("rectMicroQrVersion", params["rect_micro_qr_version"]))
        if "code128_encode_mode" in params:
            query_params.append(("code128EncodeMode", params["code128_encode_mode"]))
        if "pdf417_encode_mode" in params:
            query_params.append(("pdf417EncodeMode", params["pdf417_encode_mode"]))
        if "pdf417_error_level" in params:
            query_params.append(("pdf417ErrorLevel", params["pdf417_error_level"]))
        if "pdf417_truncate" in params:
            query_params.append(("pdf417Truncate", params["pdf417_truncate"]))
        if "pdf417_columns" in params:
            query_params.append(("pdf417Columns", params["pdf417_columns"]))
        if "pdf417_rows" in params:
            query_params.append(("pdf417Rows", params["pdf417_rows"]))
        if "pdf417_aspect_ratio" in params:
            query_params.append(("pdf417AspectRatio", params["pdf417_aspect_ratio"]))
        if "pdf417_eci_encoding" in params:
            query_params.append(("pdf417ECIEncoding", params["pdf417_eci_encoding"]))
        if "pdf417_is_reader_initialization" in params:
            query_params.append(("pdf417IsReaderInitialization", params["pdf417_is_reader_initialization"]))
        if "pdf417_macro_characters" in params:
            query_params.append(("pdf417MacroCharacters", params["pdf417_macro_characters"]))
        if "pdf417_is_linked" in params:
            query_params.append(("pdf417IsLinked", params["pdf417_is_linked"]))
        if "pdf417_is_code128_emulation" in params:
            query_params.append(("pdf417IsCode128Emulation", params["pdf417_is_code128_emulation"]))

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header "Accept"
        header_params["Accept"] = self.api_client.select_header_accept(
            [
                "image/png",
                "image/bmp",
                "image/gif",
                "image/jpeg",
                "image/svg+xml",
                "image/tiff",
                "application/json",
                "application/xml",
            ]
        )

        return self.api_client.call_api(
            "/barcode/generate/{barcodeType}",
            "GET",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="bytearray",
            auth_settings=self.auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", False),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def generate_body(self, generate_params, async_req=False, **kwargs):
        """Generate a barcode using a POST request with parameters in the request body in JSON or XML format.

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = GenerateApi().generate_body(generate_params, async_req=True)
        >>> result = thread.get()

        :param GenerateParams generate_params: Generation parameters. # noqa: E501
        :param async_req bool
        :return: bytearray
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if async_req:
            return self.generate_body_with_http_info(generate_params, **kwargs)
        else:
            data = self.generate_body_with_http_info(generate_params, **kwargs)
            return data

    def generate_body_with_http_info(self, generate_params, **kwargs):
        """Generate a barcode using a POST request with parameters in the request body in JSON or XML format.

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = GenerateApi().generate_body_with_http_info(generate_params, async_req=True)
        >>> result = thread.get()

        :param GenerateParams generate_params: Generation parameters. # noqa: E501
        :return: bytearray
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = {"generate_params"}
        all_params.add("async_req")
        all_params.add("_return_http_data_only")
        all_params.add("_preload_content")
        all_params.add("_request_timeout")

        params = locals()
        for key, val in params["kwargs"].items():
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s'" " to method generate_body" % key)
            if val is None:
                continue

            params[key] = val
        del params["kwargs"]
        # verify the required parameter "generate_params" is set
        if "generate_params" not in params or params["generate_params"] is None:
            raise ValueError("Missing the required parameter 'generate_params' when calling 'generate_body'")

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if "generate_params" in params:
            body_params = params["generate_params"]
        # HTTP header "Accept"
        header_params["Accept"] = self.api_client.select_header_accept(
            [
                "image/png",
                "image/bmp",
                "image/gif",
                "image/jpeg",
                "image/svg+xml",
                "image/tiff",
                "application/json",
                "application/xml",
            ]
        )

        # HTTP header "Content-Type"
        header_params["Content-Type"] = self.api_client.select_header_content_type(
            ["application/json", "application/xml"]
        )

        return self.api_client.call_api(
            "/barcode/generate-body",
            "POST",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="bytearray",
            auth_settings=self.auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", False),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def generate_multipart(
        self,
        barcode_type,
        data,
        data_type=None,
        barcode_image_params=None,
        qr_params=None,
        code128_params=None,
        pdf417_params=None,
        async_req=False,
        **kwargs
    ):
        """Generate a barcode using a POST request with parameters in a multipart form.

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = GenerateApi().generate_multipart(barcode_type, data, async_req=True)
        >>> result = thread.get()

        :param EncodeBarcodeType barcode_type: See https://reference.aspose.com/barcode/net/aspose.barcode.generation/encodetypes/ # noqa: E501
        :param str data: String that represents the data to encode. # noqa: E501
        :param EncodeDataType data_type: Type of data to encode. Default value: StringData. # noqa: E501
        :param BarcodeImageParams barcode_image_params: Grouped BarcodeImageParams parameters. # noqa: E501
        :param QrParams qr_params: Grouped QrParams parameters. # noqa: E501
        :param Code128Params code128_params: Grouped Code128Params parameters. # noqa: E501
        :param Pdf417Params pdf417_params: Grouped Pdf417Params parameters. # noqa: E501
        :param async_req bool
        :return: bytearray
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if async_req:
            return self.generate_multipart_with_http_info(
                barcode_type,
                data,
                data_type=data_type,
                barcode_image_params=barcode_image_params,
                qr_params=qr_params,
                code128_params=code128_params,
                pdf417_params=pdf417_params,
                **kwargs
            )
        else:
            data = self.generate_multipart_with_http_info(
                barcode_type,
                data,
                data_type=data_type,
                barcode_image_params=barcode_image_params,
                qr_params=qr_params,
                code128_params=code128_params,
                pdf417_params=pdf417_params,
                **kwargs
            )
            return data

    def generate_multipart_with_http_info(self, barcode_type, data, **kwargs):
        """Generate a barcode using a POST request with parameters in a multipart form.

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = GenerateApi().generate_multipart_with_http_info(barcode_type, data, async_req=True)
        >>> result = thread.get()

        :param EncodeBarcodeType barcode_type: See https://reference.aspose.com/barcode/net/aspose.barcode.generation/encodetypes/ # noqa: E501
        :param str data: String that represents the data to encode. # noqa: E501
        :return: bytearray
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = {
            "barcode_type",
            "data",
            "data_type",
            "barcode_image_params",
            "qr_params",
            "code128_params",
            "pdf417_params",
        }
        all_params.add("async_req")
        all_params.add("_return_http_data_only")
        all_params.add("_preload_content")
        all_params.add("_request_timeout")

        params = locals()
        for key, val in params["kwargs"].items():
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s'" " to method generate_multipart" % key)
            if val is None:
                continue

            params[key] = val
        del params["kwargs"]
        if "barcode_image_params" in params and params["barcode_image_params"].image_format is not None:
            params["image_format"] = params["barcode_image_params"].image_format
        if "barcode_image_params" in params and params["barcode_image_params"].text_location is not None:
            params["text_location"] = params["barcode_image_params"].text_location
        if "barcode_image_params" in params and params["barcode_image_params"].foreground_color is not None:
            params["foreground_color"] = params["barcode_image_params"].foreground_color
        if "barcode_image_params" in params and params["barcode_image_params"].background_color is not None:
            params["background_color"] = params["barcode_image_params"].background_color
        if "barcode_image_params" in params and params["barcode_image_params"].units is not None:
            params["units"] = params["barcode_image_params"].units
        if "barcode_image_params" in params and params["barcode_image_params"].resolution is not None:
            params["resolution"] = params["barcode_image_params"].resolution
        if "barcode_image_params" in params and params["barcode_image_params"].image_height is not None:
            params["image_height"] = params["barcode_image_params"].image_height
        if "barcode_image_params" in params and params["barcode_image_params"].image_width is not None:
            params["image_width"] = params["barcode_image_params"].image_width
        if "barcode_image_params" in params and params["barcode_image_params"].rotation_angle is not None:
            params["rotation_angle"] = params["barcode_image_params"].rotation_angle
        if "qr_params" in params and params["qr_params"].qr_encode_mode is not None:
            params["qr_encode_mode"] = params["qr_params"].qr_encode_mode
        if "qr_params" in params and params["qr_params"].qr_error_level is not None:
            params["qr_error_level"] = params["qr_params"].qr_error_level
        if "qr_params" in params and params["qr_params"].qr_version is not None:
            params["qr_version"] = params["qr_params"].qr_version
        if "qr_params" in params and params["qr_params"].qr_eci_encoding is not None:
            params["qr_eci_encoding"] = params["qr_params"].qr_eci_encoding
        if "qr_params" in params and params["qr_params"].qr_aspect_ratio is not None:
            params["qr_aspect_ratio"] = params["qr_params"].qr_aspect_ratio
        if "qr_params" in params and params["qr_params"].micro_qr_version is not None:
            params["micro_qr_version"] = params["qr_params"].micro_qr_version
        if "qr_params" in params and params["qr_params"].rect_micro_qr_version is not None:
            params["rect_micro_qr_version"] = params["qr_params"].rect_micro_qr_version
        if "code128_params" in params and params["code128_params"].code128_encode_mode is not None:
            params["code128_encode_mode"] = params["code128_params"].code128_encode_mode
        if "pdf417_params" in params and params["pdf417_params"].pdf417_encode_mode is not None:
            params["pdf417_encode_mode"] = params["pdf417_params"].pdf417_encode_mode
        if "pdf417_params" in params and params["pdf417_params"].pdf417_error_level is not None:
            params["pdf417_error_level"] = params["pdf417_params"].pdf417_error_level
        if "pdf417_params" in params and params["pdf417_params"].pdf417_truncate is not None:
            params["pdf417_truncate"] = params["pdf417_params"].pdf417_truncate
        if "pdf417_params" in params and params["pdf417_params"].pdf417_columns is not None:
            params["pdf417_columns"] = params["pdf417_params"].pdf417_columns
        if "pdf417_params" in params and params["pdf417_params"].pdf417_rows is not None:
            params["pdf417_rows"] = params["pdf417_params"].pdf417_rows
        if "pdf417_params" in params and params["pdf417_params"].pdf417_aspect_ratio is not None:
            params["pdf417_aspect_ratio"] = params["pdf417_params"].pdf417_aspect_ratio
        if "pdf417_params" in params and params["pdf417_params"].pdf417_eci_encoding is not None:
            params["pdf417_eci_encoding"] = params["pdf417_params"].pdf417_eci_encoding
        if "pdf417_params" in params and params["pdf417_params"].pdf417_is_reader_initialization is not None:
            params["pdf417_is_reader_initialization"] = params["pdf417_params"].pdf417_is_reader_initialization
        if "pdf417_params" in params and params["pdf417_params"].pdf417_macro_characters is not None:
            params["pdf417_macro_characters"] = params["pdf417_params"].pdf417_macro_characters
        if "pdf417_params" in params and params["pdf417_params"].pdf417_is_linked is not None:
            params["pdf417_is_linked"] = params["pdf417_params"].pdf417_is_linked
        if "pdf417_params" in params and params["pdf417_params"].pdf417_is_code128_emulation is not None:
            params["pdf417_is_code128_emulation"] = params["pdf417_params"].pdf417_is_code128_emulation
        # verify the required parameter "barcode_type" is set
        if "barcode_type" not in params or params["barcode_type"] is None:
            raise ValueError("Missing the required parameter 'barcode_type' when calling 'generate_multipart'")
        # verify the required parameter "data" is set
        if "data" not in params or params["data"] is None:
            raise ValueError("Missing the required parameter 'data' when calling 'generate_multipart'")

        if "resolution" in params and params["resolution"] > 100000:
            raise ValueError(
                "Invalid value for parameter 'resolution' when calling 'generate_multipart', must be a value less than or equal to '100000'"
            )
        if "resolution" in params and params["resolution"] < 1:
            raise ValueError(
                "Invalid value for parameter 'resolution' when calling 'generate_multipart', must be a value greater than or equal to '1'"
            )
        if "qr_aspect_ratio" in params and params["qr_aspect_ratio"] > 1:
            raise ValueError(
                "Invalid value for parameter 'qr_aspect_ratio' when calling 'generate_multipart', must be a value less than or equal to '1'"
            )
        if "qr_aspect_ratio" in params and params["qr_aspect_ratio"] < 0.001:
            raise ValueError(
                "Invalid value for parameter 'qr_aspect_ratio' when calling 'generate_multipart', must be a value greater than or equal to '0.001'"
            )
        if "pdf417_columns" in params and params["pdf417_columns"] > 30:
            raise ValueError(
                "Invalid value for parameter 'pdf417_columns' when calling 'generate_multipart', must be a value less than or equal to '30'"
            )
        if "pdf417_columns" in params and params["pdf417_columns"] < 0:
            raise ValueError(
                "Invalid value for parameter 'pdf417_columns' when calling 'generate_multipart', must be a value greater than or equal to '0'"
            )
        if "pdf417_rows" in params and params["pdf417_rows"] > 90:
            raise ValueError(
                "Invalid value for parameter 'pdf417_rows' when calling 'generate_multipart', must be a value less than or equal to '90'"
            )
        if "pdf417_rows" in params and params["pdf417_rows"] < 0:
            raise ValueError(
                "Invalid value for parameter 'pdf417_rows' when calling 'generate_multipart', must be a value greater than or equal to '0'"
            )
        if "pdf417_aspect_ratio" in params and params["pdf417_aspect_ratio"] > 10:
            raise ValueError(
                "Invalid value for parameter 'pdf417_aspect_ratio' when calling 'generate_multipart', must be a value less than or equal to '10'"
            )
        if "pdf417_aspect_ratio" in params and params["pdf417_aspect_ratio"] < 2:
            raise ValueError(
                "Invalid value for parameter 'pdf417_aspect_ratio' when calling 'generate_multipart', must be a value greater than or equal to '2'"
            )
        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if "barcode_type" in params:
            form_params.append(("barcodeType", params["barcode_type"]))
        if "data_type" in params:
            form_params.append(("dataType", params["data_type"]))
        if "data" in params:
            form_params.append(("data", params["data"]))
        if "image_format" in params:
            form_params.append(("imageFormat", params["image_format"]))
        if "text_location" in params:
            form_params.append(("textLocation", params["text_location"]))
        if "foreground_color" in params:
            form_params.append(("foregroundColor", params["foreground_color"]))
        if "background_color" in params:
            form_params.append(("backgroundColor", params["background_color"]))
        if "units" in params:
            form_params.append(("units", params["units"]))
        if "resolution" in params:
            form_params.append(("resolution", params["resolution"]))
        if "image_height" in params:
            form_params.append(("imageHeight", params["image_height"]))
        if "image_width" in params:
            form_params.append(("imageWidth", params["image_width"]))
        if "rotation_angle" in params:
            form_params.append(("rotationAngle", params["rotation_angle"]))
        if "qr_encode_mode" in params:
            form_params.append(("qrEncodeMode", params["qr_encode_mode"]))
        if "qr_error_level" in params:
            form_params.append(("qrErrorLevel", params["qr_error_level"]))
        if "qr_version" in params:
            form_params.append(("qrVersion", params["qr_version"]))
        if "qr_eci_encoding" in params:
            form_params.append(("qrECIEncoding", params["qr_eci_encoding"]))
        if "qr_aspect_ratio" in params:
            form_params.append(("qrAspectRatio", params["qr_aspect_ratio"]))
        if "micro_qr_version" in params:
            form_params.append(("microQRVersion", params["micro_qr_version"]))
        if "rect_micro_qr_version" in params:
            form_params.append(("rectMicroQrVersion", params["rect_micro_qr_version"]))
        if "code128_encode_mode" in params:
            form_params.append(("code128EncodeMode", params["code128_encode_mode"]))
        if "pdf417_encode_mode" in params:
            form_params.append(("pdf417EncodeMode", params["pdf417_encode_mode"]))
        if "pdf417_error_level" in params:
            form_params.append(("pdf417ErrorLevel", params["pdf417_error_level"]))
        if "pdf417_truncate" in params:
            form_params.append(("pdf417Truncate", params["pdf417_truncate"]))
        if "pdf417_columns" in params:
            form_params.append(("pdf417Columns", params["pdf417_columns"]))
        if "pdf417_rows" in params:
            form_params.append(("pdf417Rows", params["pdf417_rows"]))
        if "pdf417_aspect_ratio" in params:
            form_params.append(("pdf417AspectRatio", params["pdf417_aspect_ratio"]))
        if "pdf417_eci_encoding" in params:
            form_params.append(("pdf417ECIEncoding", params["pdf417_eci_encoding"]))
        if "pdf417_is_reader_initialization" in params:
            form_params.append(("pdf417IsReaderInitialization", params["pdf417_is_reader_initialization"]))
        if "pdf417_macro_characters" in params:
            form_params.append(("pdf417MacroCharacters", params["pdf417_macro_characters"]))
        if "pdf417_is_linked" in params:
            form_params.append(("pdf417IsLinked", params["pdf417_is_linked"]))
        if "pdf417_is_code128_emulation" in params:
            form_params.append(("pdf417IsCode128Emulation", params["pdf417_is_code128_emulation"]))

        body_params = None
        # HTTP header "Accept"
        header_params["Accept"] = self.api_client.select_header_accept(
            [
                "image/png",
                "image/bmp",
                "image/gif",
                "image/jpeg",
                "image/svg+xml",
                "image/tiff",
                "application/json",
                "application/xml",
            ]
        )

        # HTTP header "Content-Type"
        header_params["Content-Type"] = self.api_client.select_header_content_type(["multipart/form-data"])

        return self.api_client.call_api(
            "/barcode/generate-multipart",
            "POST",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="bytearray",
            auth_settings=self.auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", False),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )
