# coding: utf-8

import pprint
import re  # noqa: F401
import warnings  # noqa: F401


class Code128Params(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"code128_encode_mode": "Code128EncodeMode"}

    attribute_map = {"code128_encode_mode": "code128EncodeMode"}

    def __init__(self, code128_encode_mode=None):  # noqa: E501
        """Code128Params - a model defined in Swagger"""  # noqa: E501

        self._code128_encode_mode = None
        self.discriminator = None

        if code128_encode_mode is not None:
            self.code128_encode_mode = code128_encode_mode

    @property
    def code128_encode_mode(self):
        """Gets the code128_encode_mode of this Code128Params.  # noqa: E501

        Code128 barcode encode mode. Controls which Code 128 subset (A, B, C, or mix) is used.  # noqa: E501

        :return: The code128_encode_mode of this Code128Params.  # noqa: E501
        :rtype: Code128EncodeMode
        """
        return self._code128_encode_mode

    @code128_encode_mode.setter
    def code128_encode_mode(self, code128_encode_mode):
        """Sets the code128_encode_mode of this Code128Params.

        Code128 barcode encode mode. Controls which Code 128 subset (A, B, C, or mix) is used.  # noqa: E501

        :param code128_encode_mode: The code128_encode_mode of this Code128Params.  # noqa: E501
        :type: Code128EncodeMode
        """

        self._code128_encode_mode = code128_encode_mode

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr in self.swagger_types:
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(Code128Params, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Code128Params):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
