# coding: utf-8

import pprint
import re  # noqa: F401
import warnings  # noqa: F401


class Pdf417Params(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "pdf417_encode_mode": "Pdf417EncodeMode",
        "pdf417_error_level": "Pdf417ErrorLevel",
        "pdf417_truncate": "bool",
        "pdf417_columns": "int",
        "pdf417_rows": "int",
        "pdf417_aspect_ratio": "float",
        "pdf417_eci_encoding": "ECIEncodings",
        "pdf417_is_reader_initialization": "bool",
        "pdf417_macro_characters": "MacroCharacter",
        "pdf417_is_linked": "bool",
        "pdf417_is_code128_emulation": "bool",
    }

    attribute_map = {
        "pdf417_encode_mode": "pdf417EncodeMode",
        "pdf417_error_level": "pdf417ErrorLevel",
        "pdf417_truncate": "pdf417Truncate",
        "pdf417_columns": "pdf417Columns",
        "pdf417_rows": "pdf417Rows",
        "pdf417_aspect_ratio": "pdf417AspectRatio",
        "pdf417_eci_encoding": "pdf417ECIEncoding",
        "pdf417_is_reader_initialization": "pdf417IsReaderInitialization",
        "pdf417_macro_characters": "pdf417MacroCharacters",
        "pdf417_is_linked": "pdf417IsLinked",
        "pdf417_is_code128_emulation": "pdf417IsCode128Emulation",
    }

    def __init__(
        self,
        pdf417_encode_mode=None,
        pdf417_error_level=None,
        pdf417_truncate=None,
        pdf417_columns=None,
        pdf417_rows=None,
        pdf417_aspect_ratio=None,
        pdf417_eci_encoding=None,
        pdf417_is_reader_initialization=None,
        pdf417_macro_characters=None,
        pdf417_is_linked=None,
        pdf417_is_code128_emulation=None,
    ):  # noqa: E501
        """Pdf417Params - a model defined in Swagger"""  # noqa: E501

        self._pdf417_encode_mode = None
        self._pdf417_error_level = None
        self._pdf417_truncate = None
        self._pdf417_columns = None
        self._pdf417_rows = None
        self._pdf417_aspect_ratio = None
        self._pdf417_eci_encoding = None
        self._pdf417_is_reader_initialization = None
        self._pdf417_macro_characters = None
        self._pdf417_is_linked = None
        self._pdf417_is_code128_emulation = None
        self.discriminator = None

        if pdf417_encode_mode is not None:
            self.pdf417_encode_mode = pdf417_encode_mode
        if pdf417_error_level is not None:
            self.pdf417_error_level = pdf417_error_level
        if pdf417_truncate is not None:
            self.pdf417_truncate = pdf417_truncate
        if pdf417_columns is not None:
            self.pdf417_columns = pdf417_columns
        if pdf417_rows is not None:
            self.pdf417_rows = pdf417_rows
        if pdf417_aspect_ratio is not None:
            self.pdf417_aspect_ratio = pdf417_aspect_ratio
        if pdf417_eci_encoding is not None:
            self.pdf417_eci_encoding = pdf417_eci_encoding
        if pdf417_is_reader_initialization is not None:
            self.pdf417_is_reader_initialization = pdf417_is_reader_initialization
        if pdf417_macro_characters is not None:
            self.pdf417_macro_characters = pdf417_macro_characters
        if pdf417_is_linked is not None:
            self.pdf417_is_linked = pdf417_is_linked
        if pdf417_is_code128_emulation is not None:
            self.pdf417_is_code128_emulation = pdf417_is_code128_emulation

    @property
    def pdf417_encode_mode(self):
        """Gets the pdf417_encode_mode of this Pdf417Params.  # noqa: E501

        PDF417 barcode encode mode.  # noqa: E501

        :return: The pdf417_encode_mode of this Pdf417Params.  # noqa: E501
        :rtype: Pdf417EncodeMode
        """
        return self._pdf417_encode_mode

    @pdf417_encode_mode.setter
    def pdf417_encode_mode(self, pdf417_encode_mode):
        """Sets the pdf417_encode_mode of this Pdf417Params.

        PDF417 barcode encode mode.  # noqa: E501

        :param pdf417_encode_mode: The pdf417_encode_mode of this Pdf417Params.  # noqa: E501
        :type: Pdf417EncodeMode
        """

        self._pdf417_encode_mode = pdf417_encode_mode

    @property
    def pdf417_error_level(self):
        """Gets the pdf417_error_level of this Pdf417Params.  # noqa: E501

        PDF417 barcode error correction level.  # noqa: E501

        :return: The pdf417_error_level of this Pdf417Params.  # noqa: E501
        :rtype: Pdf417ErrorLevel
        """
        return self._pdf417_error_level

    @pdf417_error_level.setter
    def pdf417_error_level(self, pdf417_error_level):
        """Sets the pdf417_error_level of this Pdf417Params.

        PDF417 barcode error correction level.  # noqa: E501

        :param pdf417_error_level: The pdf417_error_level of this Pdf417Params.  # noqa: E501
        :type: Pdf417ErrorLevel
        """

        self._pdf417_error_level = pdf417_error_level

    @property
    def pdf417_truncate(self):
        """Gets the pdf417_truncate of this Pdf417Params.  # noqa: E501

        Whether to use truncated PDF417 format (removes right-side stop pattern).  # noqa: E501

        :return: The pdf417_truncate of this Pdf417Params.  # noqa: E501
        :rtype: bool
        """
        return self._pdf417_truncate

    @pdf417_truncate.setter
    def pdf417_truncate(self, pdf417_truncate):
        """Sets the pdf417_truncate of this Pdf417Params.

        Whether to use truncated PDF417 format (removes right-side stop pattern).  # noqa: E501

        :param pdf417_truncate: The pdf417_truncate of this Pdf417Params.  # noqa: E501
        :type: bool
        """

        self._pdf417_truncate = pdf417_truncate

    @property
    def pdf417_columns(self):
        """Gets the pdf417_columns of this Pdf417Params.  # noqa: E501

        Number of columns in the PDF417 barcode. Values between 1 and 30. 0 for auto.  # noqa: E501

        :return: The pdf417_columns of this Pdf417Params.  # noqa: E501
        :rtype: int
        """
        return self._pdf417_columns

    @pdf417_columns.setter
    def pdf417_columns(self, pdf417_columns):
        """Sets the pdf417_columns of this Pdf417Params.

        Number of columns in the PDF417 barcode. Values between 1 and 30. 0 for auto.  # noqa: E501

        :param pdf417_columns: The pdf417_columns of this Pdf417Params.  # noqa: E501
        :type: int
        """
        if pdf417_columns is not None and pdf417_columns > 30:  # noqa: E501
            raise ValueError(
                "Invalid value for `pdf417_columns`, must be a value less than or equal to `30`"
            )  # noqa: E501
        if pdf417_columns is not None and pdf417_columns < 0:  # noqa: E501
            raise ValueError(
                "Invalid value for `pdf417_columns`, must be a value greater than or equal to `0`"
            )  # noqa: E501

        self._pdf417_columns = pdf417_columns

    @property
    def pdf417_rows(self):
        """Gets the pdf417_rows of this Pdf417Params.  # noqa: E501

        Number of rows in the PDF417 barcode. Values between 3 and 90. 0 for automatic.  # noqa: E501

        :return: The pdf417_rows of this Pdf417Params.  # noqa: E501
        :rtype: int
        """
        return self._pdf417_rows

    @pdf417_rows.setter
    def pdf417_rows(self, pdf417_rows):
        """Sets the pdf417_rows of this Pdf417Params.

        Number of rows in the PDF417 barcode. Values between 3 and 90. 0 for automatic.  # noqa: E501

        :param pdf417_rows: The pdf417_rows of this Pdf417Params.  # noqa: E501
        :type: int
        """
        if pdf417_rows is not None and pdf417_rows > 90:  # noqa: E501
            raise ValueError(
                "Invalid value for `pdf417_rows`, must be a value less than or equal to `90`"
            )  # noqa: E501
        if pdf417_rows is not None and pdf417_rows < 0:  # noqa: E501
            raise ValueError(
                "Invalid value for `pdf417_rows`, must be a value greater than or equal to `0`"
            )  # noqa: E501

        self._pdf417_rows = pdf417_rows

    @property
    def pdf417_aspect_ratio(self):
        """Gets the pdf417_aspect_ratio of this Pdf417Params.  # noqa: E501

        PDF417 barcode aspect ratio (height/width of the barcode module). Values are defined by the standard: 2 to 5 for MicroPdf417; 3 to 5 for Pdf417 and MacroPdf417.  # noqa: E501

        :return: The pdf417_aspect_ratio of this Pdf417Params.  # noqa: E501
        :rtype: float
        """
        return self._pdf417_aspect_ratio

    @pdf417_aspect_ratio.setter
    def pdf417_aspect_ratio(self, pdf417_aspect_ratio):
        """Sets the pdf417_aspect_ratio of this Pdf417Params.

        PDF417 barcode aspect ratio (height/width of the barcode module). Values are defined by the standard: 2 to 5 for MicroPdf417; 3 to 5 for Pdf417 and MacroPdf417.  # noqa: E501

        :param pdf417_aspect_ratio: The pdf417_aspect_ratio of this Pdf417Params.  # noqa: E501
        :type: float
        """
        if pdf417_aspect_ratio is not None and pdf417_aspect_ratio > 10:  # noqa: E501
            raise ValueError(
                "Invalid value for `pdf417_aspect_ratio`, must be a value less than or equal to `10`"
            )  # noqa: E501
        if pdf417_aspect_ratio is not None and pdf417_aspect_ratio < 2:  # noqa: E501
            raise ValueError(
                "Invalid value for `pdf417_aspect_ratio`, must be a value greater than or equal to `2`"
            )  # noqa: E501

        self._pdf417_aspect_ratio = pdf417_aspect_ratio

    @property
    def pdf417_eci_encoding(self):
        """Gets the pdf417_eci_encoding of this Pdf417Params.  # noqa: E501

        ECI encoding for PDF417 barcode data.  # noqa: E501

        :return: The pdf417_eci_encoding of this Pdf417Params.  # noqa: E501
        :rtype: ECIEncodings
        """
        return self._pdf417_eci_encoding

    @pdf417_eci_encoding.setter
    def pdf417_eci_encoding(self, pdf417_eci_encoding):
        """Sets the pdf417_eci_encoding of this Pdf417Params.

        ECI encoding for PDF417 barcode data.  # noqa: E501

        :param pdf417_eci_encoding: The pdf417_eci_encoding of this Pdf417Params.  # noqa: E501
        :type: ECIEncodings
        """

        self._pdf417_eci_encoding = pdf417_eci_encoding

    @property
    def pdf417_is_reader_initialization(self):
        """Gets the pdf417_is_reader_initialization of this Pdf417Params.  # noqa: E501

        Whether the barcode is used for reader initialization (programming).  # noqa: E501

        :return: The pdf417_is_reader_initialization of this Pdf417Params.  # noqa: E501
        :rtype: bool
        """
        return self._pdf417_is_reader_initialization

    @pdf417_is_reader_initialization.setter
    def pdf417_is_reader_initialization(self, pdf417_is_reader_initialization):
        """Sets the pdf417_is_reader_initialization of this Pdf417Params.

        Whether the barcode is used for reader initialization (programming).  # noqa: E501

        :param pdf417_is_reader_initialization: The pdf417_is_reader_initialization of this Pdf417Params.  # noqa: E501
        :type: bool
        """

        self._pdf417_is_reader_initialization = pdf417_is_reader_initialization

    @property
    def pdf417_macro_characters(self):
        """Gets the pdf417_macro_characters of this Pdf417Params.  # noqa: E501

        Macro character to prepend (structured append).  # noqa: E501

        :return: The pdf417_macro_characters of this Pdf417Params.  # noqa: E501
        :rtype: MacroCharacter
        """
        return self._pdf417_macro_characters

    @pdf417_macro_characters.setter
    def pdf417_macro_characters(self, pdf417_macro_characters):
        """Sets the pdf417_macro_characters of this Pdf417Params.

        Macro character to prepend (structured append).  # noqa: E501

        :param pdf417_macro_characters: The pdf417_macro_characters of this Pdf417Params.  # noqa: E501
        :type: MacroCharacter
        """

        self._pdf417_macro_characters = pdf417_macro_characters

    @property
    def pdf417_is_linked(self):
        """Gets the pdf417_is_linked of this Pdf417Params.  # noqa: E501

        Whether to use linked mode (for MicroPdf417).  # noqa: E501

        :return: The pdf417_is_linked of this Pdf417Params.  # noqa: E501
        :rtype: bool
        """
        return self._pdf417_is_linked

    @pdf417_is_linked.setter
    def pdf417_is_linked(self, pdf417_is_linked):
        """Sets the pdf417_is_linked of this Pdf417Params.

        Whether to use linked mode (for MicroPdf417).  # noqa: E501

        :param pdf417_is_linked: The pdf417_is_linked of this Pdf417Params.  # noqa: E501
        :type: bool
        """

        self._pdf417_is_linked = pdf417_is_linked

    @property
    def pdf417_is_code128_emulation(self):
        """Gets the pdf417_is_code128_emulation of this Pdf417Params.  # noqa: E501

        Whether to use Code128 emulation for MicroPdf417.  # noqa: E501

        :return: The pdf417_is_code128_emulation of this Pdf417Params.  # noqa: E501
        :rtype: bool
        """
        return self._pdf417_is_code128_emulation

    @pdf417_is_code128_emulation.setter
    def pdf417_is_code128_emulation(self, pdf417_is_code128_emulation):
        """Sets the pdf417_is_code128_emulation of this Pdf417Params.

        Whether to use Code128 emulation for MicroPdf417.  # noqa: E501

        :param pdf417_is_code128_emulation: The pdf417_is_code128_emulation of this Pdf417Params.  # noqa: E501
        :type: bool
        """

        self._pdf417_is_code128_emulation = pdf417_is_code128_emulation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr in self.swagger_types:
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(Pdf417Params, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Pdf417Params):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
