# coding: utf-8

import pprint
import re  # noqa: F401
import warnings  # noqa: F401


class QrParams(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "qr_encode_mode": "QREncodeMode",
        "qr_error_level": "QRErrorLevel",
        "qr_version": "QRVersion",
        "qr_eci_encoding": "ECIEncodings",
        "qr_aspect_ratio": "float",
        "micro_qr_version": "MicroQRVersion",
        "rect_micro_qr_version": "RectMicroQRVersion",
    }

    attribute_map = {
        "qr_encode_mode": "qrEncodeMode",
        "qr_error_level": "qrErrorLevel",
        "qr_version": "qrVersion",
        "qr_eci_encoding": "qrECIEncoding",
        "qr_aspect_ratio": "qrAspectRatio",
        "micro_qr_version": "microQRVersion",
        "rect_micro_qr_version": "rectMicroQrVersion",
    }

    def __init__(
        self,
        qr_encode_mode=None,
        qr_error_level=None,
        qr_version=None,
        qr_eci_encoding=None,
        qr_aspect_ratio=None,
        micro_qr_version=None,
        rect_micro_qr_version=None,
    ):  # noqa: E501
        """QrParams - a model defined in Swagger"""  # noqa: E501

        self._qr_encode_mode = None
        self._qr_error_level = None
        self._qr_version = None
        self._qr_eci_encoding = None
        self._qr_aspect_ratio = None
        self._micro_qr_version = None
        self._rect_micro_qr_version = None
        self.discriminator = None

        if qr_encode_mode is not None:
            self.qr_encode_mode = qr_encode_mode
        if qr_error_level is not None:
            self.qr_error_level = qr_error_level
        if qr_version is not None:
            self.qr_version = qr_version
        if qr_eci_encoding is not None:
            self.qr_eci_encoding = qr_eci_encoding
        if qr_aspect_ratio is not None:
            self.qr_aspect_ratio = qr_aspect_ratio
        if micro_qr_version is not None:
            self.micro_qr_version = micro_qr_version
        if rect_micro_qr_version is not None:
            self.rect_micro_qr_version = rect_micro_qr_version

    @property
    def qr_encode_mode(self):
        """Gets the qr_encode_mode of this QrParams.  # noqa: E501

        QR barcode encode mode.  # noqa: E501

        :return: The qr_encode_mode of this QrParams.  # noqa: E501
        :rtype: QREncodeMode
        """
        return self._qr_encode_mode

    @qr_encode_mode.setter
    def qr_encode_mode(self, qr_encode_mode):
        """Sets the qr_encode_mode of this QrParams.

        QR barcode encode mode.  # noqa: E501

        :param qr_encode_mode: The qr_encode_mode of this QrParams.  # noqa: E501
        :type: QREncodeMode
        """

        self._qr_encode_mode = qr_encode_mode

    @property
    def qr_error_level(self):
        """Gets the qr_error_level of this QrParams.  # noqa: E501

        QR barcode error correction level.  # noqa: E501

        :return: The qr_error_level of this QrParams.  # noqa: E501
        :rtype: QRErrorLevel
        """
        return self._qr_error_level

    @qr_error_level.setter
    def qr_error_level(self, qr_error_level):
        """Sets the qr_error_level of this QrParams.

        QR barcode error correction level.  # noqa: E501

        :param qr_error_level: The qr_error_level of this QrParams.  # noqa: E501
        :type: QRErrorLevel
        """

        self._qr_error_level = qr_error_level

    @property
    def qr_version(self):
        """Gets the qr_version of this QrParams.  # noqa: E501

        QR barcode version. Automatically selects the smallest version that fits the data.  # noqa: E501

        :return: The qr_version of this QrParams.  # noqa: E501
        :rtype: QRVersion
        """
        return self._qr_version

    @qr_version.setter
    def qr_version(self, qr_version):
        """Sets the qr_version of this QrParams.

        QR barcode version. Automatically selects the smallest version that fits the data.  # noqa: E501

        :param qr_version: The qr_version of this QrParams.  # noqa: E501
        :type: QRVersion
        """

        self._qr_version = qr_version

    @property
    def qr_eci_encoding(self):
        """Gets the qr_eci_encoding of this QrParams.  # noqa: E501

        ECI encoding for QR barcode data.  # noqa: E501

        :return: The qr_eci_encoding of this QrParams.  # noqa: E501
        :rtype: ECIEncodings
        """
        return self._qr_eci_encoding

    @qr_eci_encoding.setter
    def qr_eci_encoding(self, qr_eci_encoding):
        """Sets the qr_eci_encoding of this QrParams.

        ECI encoding for QR barcode data.  # noqa: E501

        :param qr_eci_encoding: The qr_eci_encoding of this QrParams.  # noqa: E501
        :type: ECIEncodings
        """

        self._qr_eci_encoding = qr_eci_encoding

    @property
    def qr_aspect_ratio(self):
        """Gets the qr_aspect_ratio of this QrParams.  # noqa: E501

        QR barcode aspect ratio. Values: 0 to 1.  # noqa: E501

        :return: The qr_aspect_ratio of this QrParams.  # noqa: E501
        :rtype: float
        """
        return self._qr_aspect_ratio

    @qr_aspect_ratio.setter
    def qr_aspect_ratio(self, qr_aspect_ratio):
        """Sets the qr_aspect_ratio of this QrParams.

        QR barcode aspect ratio. Values: 0 to 1.  # noqa: E501

        :param qr_aspect_ratio: The qr_aspect_ratio of this QrParams.  # noqa: E501
        :type: float
        """
        if qr_aspect_ratio is not None and qr_aspect_ratio > 1:  # noqa: E501
            raise ValueError(
                "Invalid value for `qr_aspect_ratio`, must be a value less than or equal to `1`"
            )  # noqa: E501
        if qr_aspect_ratio is not None and qr_aspect_ratio < 0.001:  # noqa: E501
            raise ValueError(
                "Invalid value for `qr_aspect_ratio`, must be a value greater than or equal to `0.001`"
            )  # noqa: E501

        self._qr_aspect_ratio = qr_aspect_ratio

    @property
    def micro_qr_version(self):
        """Gets the micro_qr_version of this QrParams.  # noqa: E501

        MicroQR barcode version. Used when BarcodeType is MicroQR.  # noqa: E501

        :return: The micro_qr_version of this QrParams.  # noqa: E501
        :rtype: MicroQRVersion
        """
        return self._micro_qr_version

    @micro_qr_version.setter
    def micro_qr_version(self, micro_qr_version):
        """Sets the micro_qr_version of this QrParams.

        MicroQR barcode version. Used when BarcodeType is MicroQR.  # noqa: E501

        :param micro_qr_version: The micro_qr_version of this QrParams.  # noqa: E501
        :type: MicroQRVersion
        """

        self._micro_qr_version = micro_qr_version

    @property
    def rect_micro_qr_version(self):
        """Gets the rect_micro_qr_version of this QrParams.  # noqa: E501

        RectMicroQR barcode version. Used when BarcodeType is RectMicroQR.  # noqa: E501

        :return: The rect_micro_qr_version of this QrParams.  # noqa: E501
        :rtype: RectMicroQRVersion
        """
        return self._rect_micro_qr_version

    @rect_micro_qr_version.setter
    def rect_micro_qr_version(self, rect_micro_qr_version):
        """Sets the rect_micro_qr_version of this QrParams.

        RectMicroQR barcode version. Used when BarcodeType is RectMicroQR.  # noqa: E501

        :param rect_micro_qr_version: The rect_micro_qr_version of this QrParams.  # noqa: E501
        :type: RectMicroQRVersion
        """

        self._rect_micro_qr_version = rect_micro_qr_version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr in self.swagger_types:
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(QrParams, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QrParams):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
