# coding: utf-8

import pprint
import re  # noqa: F401
import warnings  # noqa: F401


class RectMicroQRVersion(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    AUTO = "Auto"
    R7X43 = "R7x43"
    R7X59 = "R7x59"
    R7X77 = "R7x77"
    R7X99 = "R7x99"
    R7X139 = "R7x139"
    R9X43 = "R9x43"
    R9X59 = "R9x59"
    R9X77 = "R9x77"
    R9X99 = "R9x99"
    R9X139 = "R9x139"
    R11X27 = "R11x27"
    R11X43 = "R11x43"
    R11X59 = "R11x59"
    R11X77 = "R11x77"
    R11X99 = "R11x99"
    R11X139 = "R11x139"
    R13X27 = "R13x27"
    R13X43 = "R13x43"
    R13X59 = "R13x59"
    R13X77 = "R13x77"
    R13X99 = "R13x99"
    R13X139 = "R13x139"
    R15X43 = "R15x43"
    R15X59 = "R15x59"
    R15X77 = "R15x77"
    R15X99 = "R15x99"
    R15X139 = "R15x139"
    R17X43 = "R17x43"
    R17X59 = "R17x59"
    R17X77 = "R17x77"
    R17X99 = "R17x99"
    R17X139 = "R17x139"

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {}

    attribute_map = {}

    def __init__(self):  # noqa: E501
        """RectMicroQRVersion - a model defined in Swagger"""  # noqa: E501
        self.discriminator = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr in self.swagger_types:
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(RectMicroQRVersion, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RectMicroQRVersion):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
